server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: CarAllocationRequest
          uri: http://localhost:8081
          predicates:
            - Path=/carAllocationRequests/** 
        - id: Driving
          uri: http://localhost:8086
          predicates:
            - Path=/drivings/** 
        - id: Payment
          uri: http://localhost:8083
          predicates:
            - Path=/payments/** 
        - id: Dashboard
          uri: http://localhost:8084
          predicates:
            - Path= /drivingInfoes/**
        - id: Message
          uri: http://localhost:8085
          predicates:
            - Path=/messages/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: CarAllocationRequest
          uri: http://CarAllocationRequest:8080
          predicates:
            - Path=/carAllocationRequests/** 
        - id: Driving
          uri: http://Driving:8080
          predicates:
            - Path=/drivings/** 
        - id: Payment
          uri: http://Payment:8080
          predicates:
            - Path=/payments/** 
        - id: Dashboard
          uri: http://Dashboard:8080
          predicates:
            - Path= /drivingInfos/**
        - id: Message
          uri: http://Message:8080
          predicates:
            - Path=/messages/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080